---
include:
  - board: nice_nano_v2
    shield: sofle-x_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: sofle-x_right
  - board: nice_nano_v2
    shield: settings_reset
  # - board: corne-v4_left
  #   snippet: studio-rpc-usb-uart
  # - board: corne-v4_right

